config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }
  get 'welcome/index'

  resources :profiles, :users

  resources :favorite_profiles, only: [:create, :destroy]

  get ':id' => 'users#show', as: :user_profile
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  match '/profiles/:id/conversations' => 'conversations#create', via: [:post]
  match '/profiles/:id/conversations/:id' => 'conversations#show', via: [:get]
  match '/profiles/:id/conversations/:conversation_id/messages' => 'messages#create', via: [:post]

   root 'welcome#index'

   resources :conversations do
    resources :messages
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #before_filter :signed_in_user, only: [:index]
  belongs_to :user

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: "/images/avatarph.png"
  validates_attachment :avatar, content_type: { content_type: /\Aimage\/.*\Z/ },
                                size: { in: 0..1.megabytes }

  has_attached_file :photo1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/camplaceholder.png"
  validates_attachment_content_type :photo1, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/camplaceholder.png"
  validates_attachment_content_type :photo2, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo3, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/camplaceholder.png"
  validates_attachment_content_type :photo3, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo4, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/camplaceholder.png"
  validates_attachment_content_type :photo4, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo5, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/camplaceholder.png"
  validates_attachment_content_type :photo5, content_type: /\Aimage\/.*\Z/

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  helper_method :own_record

  # GET /profiles
  # GET /profiles.json
  # def index
  #   @profiles = Profile.all
  # end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    @userid = @profile.user_id
    @user = User.find(@userid)
    @sex = @user.sex

      @previous = Profile.joins(:user).where("profiles.id < ? AND sex!=?", params[:id], current_user.sex).order(:id).first
      @next = Profile.joins(:user).where("profiles.id > ? AND sex !=?", params[:id], current_user.sex).order(:id).first
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    if @profile.user_id != current_user.id
      redirect_to(profile_path(current_user.id))
    end
  end

  def own_record
     if current_user.id == @profile.user_id
       true
     end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      if Profile.exists?(:user_id => current_user.id)
        @profile = Profile.find(params[:id])
      else
        redirect_to new_profile_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:phone, :occupation, :education, :hobbies, :bio, :location, :relationship, :avatar, :photo1, :photo2, :photo3, :photo4, :photo5)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship %>
  </div>
<br> <br>
  <div class="">
    <%= f.submit "Update Profile", class:"ghost" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h2 class="username">Edit your Profile</h2>
<section id="edit" class="">

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render 'form' %>

      <%= link_to 'Show', @profile %> |
      <!-- <%= link_to 'Back', profiles_path %> -->
    </div>
  </div>
</div>

</section>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Occupation</th>
      <th>Education</th>
      <th>Hobbies</th>
      <th>Bio</th>
      <th>Location</th>
      <th>Relationship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |person| %>
      <tr>

        <td><%= person.phone %></td>
        <td><%= person.occupation %></td>
        <td><%= person.education %></td>
        <td><%= person.hobbies %></td>
        <td><%= person.bio %></td>
        <td><%= person.location %></td>
        <td><%= person.relationship %></td>

        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_profile_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<section id="complete">
        <div class="profcard col-md-10 col-md-offset-1">

        </div>

<!-------------------Tabs---------------------->

    <div class="container">
            <div class="board2">
              <div class="greystrip">
                 <ul class="nav nav-tabs text-center col-md-10 col-md-offset-1" id="tabs" data-tabs="tabs">
                   <div class="liner"></div>
                    <li class="active"><a href="#location" data-toggle="tab" title="Location"><span class="round-tabs"><i class="fa fa-map-marker fa-3x"></i></span></a> </li>

                    <li><a href="#rship" data-toggle="tab" title="Relationship Status"><span class="round-tabs"><i class="fa fa-heart fa-3x"></i></span></a> </li>

                    <li><a href="#hobbies" data-toggle="tab" title="Hobbies & Interests"><span class="round-tabs"><i class="fa fa-soccer-ball-o fa-3x"></i></span></a> </li>

                     <li><a href="#occupation" data-toggle="tab" title="Occupation"><span class="round-tabs"><i class="fa fa-briefcase fa-3x"></i></span></a></li>

                    <li><a href="#education" data-toggle="tab" title="Education"><span class="round-tabs"><i class="fa fa-graduation-cap fa-3x"></i></span></a></li>

                    <li><a href="#phone" data-toggle="tab" title="Bio"><span class="round-tabs"><i class="fa fa-phone fa-3x"></i></span></a> </li>

                    <li><a href="#avi" data-toggle="tab" title="Avi"><span class="round-tabs"><i class="fa fa-camera-retro fa-3x"></i></span></a> </li>
                </ul>
              </div>
               <%= form_for(@profile) do |f| %>
               <% if @profile.errors.any? %>
                 <div id="error_explanation">
                   <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this person from being saved:</h2>

                   <ul>
                   <% @profile.errors.full_messages.each do |message| %>
                     <li><%= message %></li>
                   <% end %>
                   </ul>
                 </div>
               <% end %>

                 <div class="tab-content">
                      <div class="tab-pane fade in active" id="location">
                        <p class="narrow text-center">Hi <%= current_user.name.split(' ').first %>, Tell me a little more about yourself. Where do you live?</p><br/>
                        <%= f.text_field :location, class: "col-md-offset-3"%><br> <br>
                        <span class="progress">
                          <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x col-md-4"></i> <a href="#rship"><i class="fa fa-check fa-2x col-md-2"></i></a>
                        </span>
                      </div>
                      <div class="tab-pane fade" id="rship"><p class="narrow text-center">What is your current relationship status?</p><br/>
                          <%= f.radio_button(:relationship, "Single") %>
                          <%= label_tag(:relationship_single, "Single") %><br>
                          <%= f.radio_button(:relationship, "Divorced") %>
                          <%= label_tag(:relationship_divorced, "Divorced") %><br>
                          <%= f.radio_button(:relationship, "Widowed") %>
                          <%= label_tag(:relationship_widowed, "Widowed") %><br>
                          <%= f.radio_button(:relationship, "In a r/ship") %>
                          <%= label_tag(:relationship_relationship, "In a relationship") %><br>
                          <%= f.radio_button(:relationship, "Open r/ship") %>
                          <%= label_tag(:relationship_open, "Open Relationship") %><br>
                          <%= f.radio_button(:relationship, "Complicated") %>
                          <%= label_tag(:relationship_complicated, "It's complicated") %><br> <br> <br> <br> <br>
                          <span class="progress">
                            <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x col-md-4"></i><i class="fa fa-check fa-2x col-md-2"></i>
                          </span>
                      </div>

                      <div class="tab-pane fade" id="occupation"><p class="narrow text-center">What is your occupation?</p><br/>
                        <%= f.text_field :occupation, class: "col-md-offset-3"%><br> <br>
                        <span class="progress">
                          <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x  col-md-4"></i><i class="fa fa-check fa-2x  col-md-2"></i>
                        </span>
                      </div>

                      <div class="tab-pane fade" id="education"><p class="narrow text-center">What is your highest level of educational attainment?</p><br/>
                          <%= f.radio_button(:education, "Primary School") %>
                          <%= label_tag(:education_primary, "Primary School") %><br>
                          <%= f.radio_button(:education, "Secondary School") %>
                          <%= label_tag(:education_secondary, "Secondary School") %><br>
                          <%= f.radio_button(:education, "College") %>
                          <%= label_tag(:education_college, "College") %><br>
                          <%= f.radio_button(:education, "University") %>
                          <%= label_tag(:education_university, "University") %><br>
                          <%= f.radio_button(:education, "Postgraduate") %>
                          <%= label_tag(:education_postgraduate, "Postgraduate") %><br> <br> <br> <br> <br> <br>
                          <span class="progress">
                            <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x col-md-4"></i><i class="fa fa-check fa-2x col-md-2"></i>
                          </span>
                      </div>

                      <div class="tab-pane fade" id="hobbies"><p class="narrow text-center">What do you like to do at your free time?</p><br/>
                        <%= f.text_field :hobbies, class: "col-md-offset-3"%><br> <br>
                        <span class="progress">
                          <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x col-md-4"></i><i class="fa fa-check fa-2x col-md-2"></i>
                        </span>
                      </div>

                      <div class="tab-pane fade" id="phone"><p class="narrow text-center">Now <%= current_user.name.split(' ').first %>, would you mind giving me your phone number?
                      (Your contact details will not be displayed without your permission)</p><br/>
                        <%= f.text_field :phone, class: "col-md-offset-3"%><br> <br>
                        <span class="progress">
                          <i class="fa fa-long-arrow-left fa-2x col-md-6"></i><i class="fa fa-close fa-2x col-md-4"></i><i class="fa fa-check fa-2x col-md-2"></i>
                        </span>
                      </div>

                      <div class="tab-pane fade" id="avi"><p class="narrow text-center">Finally, please upload your avatar<br/>
                        <%= f.file_field :avatar %><br><br>



                        <%= f.submit "Save Profile", class: "btn btn-primary", :width => 60%>
                      </div>
                </div>
                 <% end %>
          </div>
    </div>

<!---------------------------------Tabs-------------->

</section>


<section id="mobileview">
  <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 form-area">
          <%= form_for(@profile) do |f| %>
            <div class="form-group">
              <%= f.label :phone %><br>
              <%= f.text_field :phone, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :occupation %><br>
              <%= f.text_field :occupation, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :education %><br>
              <%= f.text_field :education, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :hobbies %><br>
              <%= f.text_field :hobbies, class:"form-control" %>
            </div>
            
            <div class="form-group">
              <%= f.label :location %><br>
              <%= f.text_field :location, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :relationship %><br>
              <%= f.text_field :relationship, class:"form-control" %>
            </div>
          <br> <br>
            <div class="">
              <%= f.submit "Save Profile", class:"ghost" %>
            </div>
          <% end %>

        </div>
      </div>
  </div>
</section>

app/views/profiles/show.html.erb
<h2 class="username"><%= @user.name%></h2>
<section id="profile">
  <div class="modal fade" id="my-modal" title="My modal">
      <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h3 id="myModalLabel">Upload profile pictures</h3>
      </div>
      <div class="modal-body">
        <%= form_for(@profile) do |f| %>
          Photo 1: <%= f.file_field :photo1 , class: "btn btn-primary"%><br>
          Photo 2: <%= f.file_field :photo2 , class: "btn btn-primary"%><br>
          Photo 3: <%= f.file_field :photo3 , class: "btn btn-primary"%><br>
          Photo 4: <%= f.file_field :photo4 , class: "btn btn-primary"%><br>
          Photo 5: <%= f.file_field :photo5 , class: "btn btn-primary"%>

      </div>
      <div class="modal-footer">
          <%= f.submit "Save Images", class: "btn btn-primary" %>
        <% end %>
        <!-- <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button> -->
      </div>
  </div>
          <div class="profcard col-md-10 col-md-offset-1">
          <div class="row">
            <div class="col-md-3 col-md-offset-1 left-title">
              <% if mark_favorite%>
                <%= link_to favorite_profile_path(profile_id: @profile), method: :delete do%>
                  <i class="fa fa-heart" title="favourite"></i>
                <%end%>
              <%else%>
                <%= link_to favorite_profiles_path(profile_id: @profile), method: :post do%>
                  <i class="fa fa-heart-o" title="favourite"></i>
                <%end%>
              <%end%>
              <%= link_to "#", class: "start-conversation", "data-sid" => current_user.id, "data-rip" => @user.id do%>
                <i class="fa fa-comments-o" title="chat"></i>
              <%end%>
              <i class="fa fa-film" title="videos"></i>
            </div>
            <div class="col-md-4  text-center">
              <% if @profile.avatar %>
                <%= image_tag @profile.avatar.url, :class => "img-circle" %>
              <% else %>
                  <img src="/assets/avatarph-aac822842b411310cb92f1b736c7048c09581d6a72a8304a3e964a5c3931da08.png" class="img-circle" alt="" />
              <% end %>

            </div>
            <div class="col-md-3">
              <div class="details">
                <div><strong>Age: <%= @user.age %> </strong> </div>
                <div><strong>Relationship:</strong> <%= @profile.relationship %></div>
                <div><strong>Location:</strong> <%= @profile.location %></div>
              </div>


            </div>
          </div>
          <hr width="80%" color="#110026">
          <div class="row">

            <div class="text-center col-md-10 col-md-offset-1">
            <%if own_record %> <span class="modallink"> <%= link_to "Upload Photo", "#my-modal", :class => "btn", "data-toggle" => "modal" %> </span><% end %> <%= image_tag @profile.photo1.url, :class => "imgstrip" %>
            <%if own_record %> <span class="modallink"> <%= link_to "Upload Photo", "#my-modal", :class => "btn", "data-toggle" => "modal" %> </span><% end %>  <%= image_tag @profile.photo2.url, :class => "imgstrip" %>
            <%if own_record %> <span class="modallink"> <%= link_to "Upload Photo", "#my-modal", :class => "btn", "data-toggle" => "modal" %> </span><% end %>  <%= image_tag @profile.photo3.url, :class => "imgstrip" %>
            <%if own_record %> <span class="modallink"> <%= link_to "Upload Photo", "#my-modal", :class => "btn", "data-toggle" => "modal" %> </span><% end %>  <%= image_tag @profile.photo4.url, :class => "imgstrip" %>
            <%if own_record %> <span class="modallink"> <%= link_to "Upload Photo", "#my-modal", :class => "btn", "data-toggle" => "modal" %> </span><% end %>  <%= image_tag @profile.photo5.url, :class => "imgstrip" %>
            </div>
          </div>
        </div>
      <div class="container">
        <div class="row">
          <div class="col-md-1 caretleft">
            <%if @previous%>
              <%= link_to @previous do %>
                <i class="fa fa-angle-left fa-5x" title="previous"></i>
              <%end%>
            <% end %>
          </div>
          <div class="col-md-1 caretright">
            <%if @next%>
              <%= link_to @next do %>
                <i class="fa fa-angle-right fa-5x" title="next"></i>
              <%end%>
            <%end %>
          </div>
        </div>
      </div>
  <!-------------------Tabs---------------------->

      <div class="container">
              <div class="board">
                <span class="showtabs">
                   <ul class="nav nav-tabs text-center col-md-10 col-md-offset-1" id="tabs" data-tabs="tabs">
                      <li class="active"><a href="#phone" data-toggle="tab" title="Phone Number"><span class="round-tabs2"><i class="fa fa-phone fa-3x"></i><br/>PHONE</span></a> </li>

                      <li><a href="#email" data-toggle="tab" title="Email Address"><span class="round-tabs2"><i class="fa fa-envelope fa-3x"></i><br/>EMAIL</span></a> </li>

                       <li><a href="#occupation" data-toggle="tab" title="Occupation"><span class="round-tabs2"><i class="fa fa-briefcase fa-3x"></i><br/>OCCUPATION</span></a></li>

                      <li><a href="#education" data-toggle="tab" title="Education"><span class="round-tabs2"><i class="fa fa-graduation-cap fa-3x"></i><br/>EDUCATION</span></a></li>

                       <li><a href="#hobbies" data-toggle="tab" title="Hobbies &amp; Interests"><span class="round-tabs2"><i class="fa fa-soccer-ball-o fa-3x"></i><br/>HOBBIES</span></a> </li>

                      <li><a href="#bio" data-toggle="tab" title="Bio"><span class="round-tabs2"><i class="fa fa-user fa-3x"></i><br/>BIO</span></a> </li>
                  </ul>
                </span>
                   <div class="tab-content browseprof">
                        <div class="tab-pane fade in active" id="phone"><p class="narrow text-center"><%= @profile.phone %></p></div>

                        <div class="tab-pane fade" id="email"><p class="narrow text-center"><%= @user.email%></p></div>

                        <div class="tab-pane fade" id="occupation"><p class="narrow text-center"><%= @profile.occupation %></p></div>

                        <div class="tab-pane fade" id="education"><p class="narrow text-center"><%= @profile.education %></p></div>

                        <div class="tab-pane fade" id="hobbies"><p class="narrow text-center"><%= @profile.hobbies %></p></div>

                        <div class="tab-pane fade" id="bio"><p class="narrow text-center"><%= @profile.bio %></p></div>
                  </div>
            </div>
      </div>

  <!---------------------------------Tabs-------------->

</section>

<section id="mobileview">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-5">
        <% if @profile.avatar %>
          <%= image_tag @profile.avatar.url(:thumb), :class => "img-circle" %>
        <% else %>
            <img src="/assets/images/avatarphsmall.png"  alt=""/>
        <% end %>
      </div>
      <div class="col-xs-7">
        <div class="details">
          <div><strong>Age: <%= @user.age %> </strong> </div>
          <div><strong>Relationship:</strong> <%= @profile.relationship %></div>
          <div><strong>Location:</strong> <%= @profile.location %></div>
        </div>
        <div class="left-title">
          <% if mark_favorite%>
            <%= link_to favorite_profile_path(profile_id: @profile), method: :delete do%>
              <i class="fa fa-heart" title="favourite"></i>
            <%end%>
          <%else%>
            <%= link_to favorite_profiles_path(profile_id: @profile), method: :post do%>
              <i class="fa fa-heart-o" title="favourite"></i>
            <%end%>
          <%end%>
          <%= link_to "#", class: "start-conversation", "data-sid" => current_user.id, "data-rip" => @user.id do%>
            <i class="fa fa-comments-o" title="chat"></i>
          <%end%>
        </div>

      </div>
    </div>
    <span class="mobdetails">
      <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-phone"></i><br/> <strong>Phone</strong>
          </div>
          <div class="col-xs-8">
            <span> <%= @profile.phone %> </span>
          </div>
      </div>

      <div class="row">
        <div class="col-xs-4">
          <i class="fa fa-envelope"></i><br/> <strong>Email</strong>
        </div>
        <div class="col-xs-8">
          <span> <%= @user.email%> </span>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4">
          <i class="fa fa-briefcase"></i><br/> <strong>Occupation</strong>
        </div>
        <div class="col-xs-8">
          <span> <%= @profile.occupation %> </span>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4">
          <i class="fa fa-graduation-cap fa-3x"></i><br/> <strong>Education</strong>
        </div>
        <div class="col-xs-8">
          <span> <%= @profile.education %> </span>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-4">
          <i class="fa fa-soccer-ball-o fa-3x"></i><br/> <strong>Hobbies</strong>
        </div>
        <div class="col-xs-8">
          <span> <%= @profile.hobbies %> </span>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-9">
          <%if @previous%>
            <%= link_to 'Previous', @previous %>
              <!-- <i class="fa fa-angle-left fa-5x" title="previous"></i> -->

          <% end %>
        </div>

        <div class="col-xs-3">
          <%if @next%>
            <%= link_to 'Next', @next  %>
              <!-- <i class="fa fa-angle-right fa-5x" title="next"></i> -->
          <%end %>
        </div>
      </div>
    </span>
  </div>
</section>



<!--# <%= link_to 'Edit', edit_profile_path(@profile) %> |
# <%= link_to 'Back', profiles_path %>-->