config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }
  get 'welcome/index'

  resources :profiles, :users

  resources :favorite_profiles, only: [:create, :destroy]

  get ':id' => 'users#show', as: :user_profile
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  match '/profiles/:id/conversations' => 'conversations#create', via: [:post]
  match '/profiles/:id/conversations/:id' => 'conversations#show', via: [:get]
  match '/profiles/:id/conversations/:conversation_id/messages' => 'messages#create', via: [:post]

   root 'welcome#index'

   resources :conversations do
    resources :messages
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @people = @q.result(distinct: true)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<section id="home">
  <div class="modal fade" id="my-modal" title="My modal">
      <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h3 id="myModalLabel">Account Confirmation</h3>
      </div>
      <div class="modal-body">
        <p>
          Congratulations, your account has been created. Now head over to your email address to confirm your account.
        </p>

      </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <% if ! user_signed_in?%>
      <div class="col-md-offset-7 col-md-3 col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-6 signup">

        <h2>SIGN UP</h2>

        <%= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name), label_errors: true) do |f| %>
          <%= devise_error_messages! %>

          <div class="field">
            <%= f.text_field_without_bootstrap :name, autofocus: true, :autocomplete => :off %>
            <%= f.label :name %>
          </div>

          <div class="field">
            <label for="user_sex">I'm a : </label>
            <span class="kati">
              <%= f.radio_button(:sex, "male") %>
              <i class="fa fa-male fa-2x icpurple"></i>
              <%= f.radio_button(:sex, "female") %>
              <i class="fa fa-female fa-2x icpurple"></i>
            </span>
          </div>

          <div class="field">
            <%= f.text_field_without_bootstrap :age, :autocomplete => :off%>
            <%= f.label :age %>
          </div>

          <div class="field">
            <%= f.email_field_without_bootstrap :email, :autocomplete => :off %>
            <%= f.label :email %>
          </div>

          <div class="field">
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %>
            <%= f.password_field_without_bootstrap :password, autocomplete: "off" %>
            <%= f.label :password %>
          </div>

          <div class="actions">
            <%= f.submit "GET STARTED", class: "ghost registerbtn"%>
          </div>
          <br> <br> <br>
          <%= link_to image_tag('fblogin.png') .html_safe, user_omniauth_authorize_path(:facebook)%>
        <% end %>

      </div>


      <% end %>


      <% if user_signed_in?%>
        <div class="dash">
          <h2 class="result-title"></h2>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-3 col-md-offset-2 col-xs-5 text-center notifications">
                <i class="fa fa-heart fa-2x"></i><br><span>
                  Favorites
                </span>
              </div>
              <div class="col-md-3 col-md-offset-2 col-xs-5 col-xs-offset-2 text-center notifications">
                <i class="fa fa-comments-o fa-2x"></i><br><span>
                  Messages
                </span>
              </div>
            </div>
            <br> <br> <br>
            <div class="row">
              <% if Profile.present?%>
                <%=link_to profile_path(current_user.profile.id ) do %>
                  <div class="col-md-3 col-md-offset-2 col-xs-5 text-center notifications">
                    <i class="fa fa-user fa-2x"></i><br><span>
                      Profile
                    </span>
                  </div>
                <%end%>
              <%end%>
              <div class="col-md-3 col-md-offset-2 col-xs-5 col-xs-offset-2 text-center notifications search">
                <i class="fa fa-search fa-2x"></i><br><span>
                  Search
                </span>
              </div>
            </div>
          </div>
        </div>
      <%end%>

    </div>
  </div>


    <div class="searchbar col-md-8 col-md-offset-2">
      <%if false%>
        <%= search_form_for @q , class:"input-group stylish-input-group" do |f| %>
          <%= f.search_field :name_cont, class: "form-control search-term", placeholder: "Search for your lover" %>
          <span class="input-group-addon">
          <%= f.submit 'Search', class: "searchbtn" %>
          </span>
        <%end%>
      <%end%>

      <%= search_form_for @q, class:"input-group stylish-input-group" do |f| %>
        <%= f.search_field :name_cont, class: "form-control search-term", placeholder: "Search for people" %>
      <span class="input-group-addon">
        <%= f.submit %>
      </span>
      <%end%>
    </div>


</section>
<% if !user_signed_in? %>
<section id="how">
  <div class="whitelayer">
    <div class="container-fluid">
        <h1 class="text-center">How it works</h1>
      <div class="row">
        <div class="col-md-offset-3 col-md-2 text-center"><%= image_tag('register.png') %></div>
        <div class="col-md-4">
          <h2><strong>1. Register for free</strong></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-offset-3 col-md-2 text-center">
          <%= image_tag('browse.png') %>
        </div>
        <div class="col-md-4">
          <h2><strong>2. Browse member profiles</strong></h2>
          <p>Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-offset-3 col-md-2 text-center"><%= image_tag('match.png') %></div>
        <div class="col-md-4">
          <h2><strong>3. Find your match</strong></h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="plans">
  <div class="semilayer">
    <h1 class="text-center">Plans & Pricing</h1>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-offset-2 col-md-3">
          <div class="basictitle">
            <h2>BASIC</h2>
          </div>
          <div class="basicbody">
            <ul>
              <li><i class="fa fa-edit fa-lg"></i>  Free Registration</li>
              <li><i class="fa fa-camera fa-lg"></i>  Upload 5 photos</li>
              <li><i class="fa fa-video-camera fa-lg"></i>  Upload 1 video</li>
              <li><i class="fa fa-comments-o fa-lg"></i>  Chat with basic users</li>
              <li><i class="fa fa-users fa-lg"></i>  View basic users' profiles</li>
              <li><i class="fa fa-money fa-lg"></i>  Free</li>
            </ul>
          </div>
        </div>
        <div class="col-md-offset-2 col-md-3">
          <div class="premiumtitle">
            <h2>PREMIUM</h2>
          </div>
          <div class="premiumbody">
            <ul>
              <li><i class="fa fa-edit fa-lg"></i>  All basic features</li>
              <li><i class="fa fa-cloud-upload fa-lg"></i>  Unlimited uploads</li>
              <li><i class="fa fa-user-secret fa-lg"></i>  See who viewed your profile</li>
              <li><i class="fa fa-user-plus fa-lg"></i>  Get matched with similar interest users</li>
              <li><i class="fa fa-money fa-lg"></i>  KES 888</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="social">
  <div class="blacklayer">
    <div class="container-fluid">
        <h1 class="text-center">We are social</h1>
      <div class="row text-center social-icons">
        <div class="col-md-3"><i class="fa fa-facebook-square fa-5x"></i></div>
        <div class="col-md-3"><i class="fa fa-twitter-square fa-5x"></i></div>
        <div class="col-md-3"><i class="fa fa-youtube-square fa-5x"></i></div>
        <div class="col-md-3"><i class="fa fa-instagram fa-5x"></i></div>
      </div>
      <div class="row rule">
        <div class="col-md-offset-1 col-md-10">
          <hr/>
          <p class="text-center">&copy; <%= Time.now.year %></p>
        </div>
      </div>
    </div>
  </div>
</section>
<%end%>