config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations' }
  get 'welcome/index'

  resources :profiles, :users

  resources :favorite_profiles, only: [:create, :destroy]

  get ':id' => 'users#show', as: :user_profile
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  match '/profiles/:id/conversations' => 'conversations#create', via: [:post]
  match '/profiles/:id/conversations/:id' => 'conversations#show', via: [:get]
  match '/profiles/:id/conversations/:conversation_id/messages' => 'messages#create', via: [:post]

   root 'welcome#index'

   resources :conversations do
    resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <title>Xiv2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'mystyles'%>
  <%= stylesheet_link_tag    'chat'%>
  <%= stylesheet_link_tag    'mobile'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="viewport" content="width=device-width, target-densityDpi=device-dpi">
</head>
<body>
  <header>
    <nav role="navigation" class="navbar navbar-inverse">
          <div class="navbar-header">
              <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <% if current_page?("/") %>
                <h2>XIV</h2>
              <% elsif current_page?(new_profile_path)%>
                <h2>Complete your profile</h2>
              <% else %>
                  <% if user_signed_in? %>
                  <h2><%=  %></h2>
                  <%end%>
              <%end%>


          </div>

          <div id="navbarCollapse" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">

              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a class="round-ghost">UPGRADE</a></li>
                <li><i class="fa fa-bell-o fa-2x"></i></li>
                <li><i class="fa fa-envelope-o fa-2x"></i></li>
                <li> <% if params[:controller]=='profiles' &&  @profile.id !=nil%>
                    <%= link_to '<i class="fa fa-gears fa-2x"></i>'.html_safe, edit_profile_path , :class=> 'setlink'%>
                <% end%></li>

                <li>
                    <img class="avi" src="/assets/avatarph-aac822842b411310cb92f1b736c7048c09581d6a72a8304a3e964a5c3931da08.png"/>
                </li>
              </ul>
              <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                        <a href="/">Home</a>
                   <!-- <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | -->
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                  <!-- <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | -->
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                <% end %>
              </p>
          </div>
      </nav>
  </header>


<%= yield %>
<audio id="chatAudio"><source src="/sounds/notify.mp3" type="audio/mpeg"></audio>

  <% if current_user %>
    <script type="text/javascript">
        channel = <%= raw ('"' + '/notifications' + current_user.id.to_s + '"') %>
        PrivatePub.subscribe(channel, function(data) {

        var sender_id = data.sid;
        var recipient_id = data.rip;
        var conversation_id = data.cid;


        $.post("/conversations", { sender_id: sender_id, recipient_id: recipient_id }, function (data) {
            chatBox.chatWith(conversation_id);
        });

        });
    </script>
    <%= subscribe_to "/notifications" + current_user.id.to_s %>
  <% end %>

</body>
</html>